language: php
git:
  submodules: false

services:
  - docker

before_install:
  - docker pull composer
  - docker pull php
  - docker run -v `pwd`:/app composer /bin/sh -c "php composer.phar install"
  - nvm install 12.0
  - npm install --global prettier

script:
  - docker run -v `pwd`:/app -w /app php /bin/sh -c "./phpcs.sh"
  - cd frontend && prettier -l .
