version: "3.2"
services:
  api:
    image: node:latest
    ports:
      - "443:4096"
      # - "3001:3001"
    volumes:
      - ../api:/app
      - ./wait-for-it.sh:/wait-for-it.sh
    user: "1000"
    # make the API wait for mysql and Hasura to start first
    command: ./wait-for-it.sh mysql:3306 -t 60 -- ./wait-for-it.sh graphql-engine:8080 -t 60 -- sh -cx 'cd /app && yarn && yarn prod'

    depends_on:
      - graphql-engine
      - mysql
    environment:
      GRAPHQL_ENDPOINT: http://graphql-engine:8080/v1/graphql
      FRONTEND_ENDPOINT: ${FRONTEND_ENDPOINT?frontend_endpoint}
      NODE_ENV: production
      MYSQL_HOST: ${MYSQL_HOST?host}
      MYSQL_PORT: ${MYSQL_PORT?port}
      MYSQL_USER: ${MYSQL_USERNAME?username}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD?password}
      MYSQL_URL: ${MYSQL_URL?mysql_url}
      STUDENTS_DB: yaleplus
      COURSES_DB: yale_advanced_oci
      CHALLENGE_PASSWORD: ${CHALLENGE_ENC_PASSWORD?challenge password}
      SESSION_SECRET: ${SESSION_SECRET?session secret}
      FERRY_SECRET: ${FERRY_RELOAD_SECRET?ferry reload secret}
      YALIES_API_KEY: ${YALIES_API_KEY?yalies_api_key}
      CERT_PATH: ${CERT_PATH?cert_path}
      KEY_PATH: ${KEY_PATH?key_path}
      FACEBOOK_API_ENDPOINT: ${FACEBOOK_API_ENDPOINT?facebook_api_endpoint}

  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    environment:
      HASURA_GRAPHQL_DATABASE_URL: ${FERRY_POSTGRES_URI?ferry db}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey

  nginx:
    build: ./nginx
    volumes:
      - ..:/usr/share/nginx/html
      # Overwrite the default configuration. Our conf is based on it
      - ../sysadmin/nginx/docker:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
      - mysql
    links:
      - php-fpm

  mysql:
    build: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD?password}
    volumes:
      # This will get used to initialize the database: see
      # "Initializing a fresh instance"
      # in https://hub.docker.com/_/mariadb
      - ./mysql/database.sql:/docker-entrypoint-initdb.d/00-database.sql

  phpmyadmin:
    build: ./phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD?password}
    ports:
      - "8081:80"

  legacy:
    image: nginx
    volumes:
      - ../legacy:/usr/share/nginx/html:ro
