version: "3.2"
services:
  api:
    image: node:latest
    ports:
      - "443:4096"
      # - "3001:3001"
    volumes:
      - ../api:/app
      - ./wait-for-it.sh:/wait-for-it.sh
    # make the API wait for mysql and Hasura to start first
    command: ./wait-for-it.sh mysql:3306 -t 60 -- ./wait-for-it.sh graphql-engine:8080 -t 60 -- sh -cx 'cd /app && yarn && yarn prod'

    depends_on:
      - graphql-engine
      - mysql
    environment:
      CERT_PATH: ${CERT_PATH?cert_path}
      CHALLENGE_PASSWORD: ${CHALLENGE_ENC_PASSWORD?challenge password}
      FACEBOOK_API_ENDPOINT: ${FACEBOOK_API_ENDPOINT?facebook_api_endpoint}
      FERRY_SECRET: ${FERRY_RELOAD_SECRET?ferry_reload_secret}
      FRONTEND_ENDPOINT: ${FRONTEND_ENDPOINT?frontend_endpoint}
      GRAPHQL_ENDPOINT: http://graphql-engine:8080/v1/graphql
      KEY_PATH: ${KEY_PATH?key_path}
      MYSQL_HOST: ${MYSQL_HOST?host}
      MYSQL_PORT: ${MYSQL_PORT?port}
      MYSQL_USER: ${MYSQL_USERNAME?username}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD?password}
      MYSQL_URL: ${MYSQL_URL?mysql_url}
      NODE_ENV: production
      SESSION_SECRET: ${SESSION_SECRET?session_secret}
      STUDENTS_DB: yaleplus
      YALIES_API_KEY: ${YALIES_API_KEY?yalies_api_key}
    labels:
      traefik.enable: true
      traefik.http.routers.coursetable.rule: Host(`api.coursetable.com`)
      traefik.http.routers.coursetable.tls: true
      traefik.http.routers.coursetable.tls.certResolver: ctresolver
      traefik.http.routers.coursetable.middlewares: gzip-compress@file
    networks:
      - traefik
      - mysql_default
      - default

  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    environment:
      HASURA_GRAPHQL_DATABASE_URL: ${FERRY_POSTGRES_URI?ferry_db}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    networks:
      - ferry_default
      - default

  legacy:
    image: nginx
    restart: always
    ports:
      - "8075:80"
    volumes:
      - ../legacy:/usr/share/nginx/html:ro
    labels:
      traefik.enable: true
      traefik.http.routers.coursetable-legacy.rule: Host(`legacy.coursetable.com`)
      traefik.http.routers.coursetable-legacy.tls: true
      traefik.http.routers.coursetable-legacy.tls.certResolver: ctresolver
    networks:
      - traefik
      - default

networks:
  traefik:
    external: true
  ferry_default:
    external: true
  mysql_default:
    external: true
