version: '3.2'
services:
  proxy:
    image: node:latest
    restart: always
    ports:
      - '8039:8039'
      - '8038:8080'
    expose:
      - 8039
    volumes:
      - ../dev_proxy:/app
    user: '1000'
    command: sh -c 'cd /app && yarn && yarn start'
    environment:
      FRONTEND_LOC: 'http://frontend:5000'
      PORT: 8039
    links:
      - frontend
      - api
      - nginx
    labels:
      traefik.enable: true
      traefik.http.routers.coursetable.rule: Host(`coursetable.com`)
      traefik.http.routers.coursetable.tls: true
      traefik.http.routers.coursetable.tls.certResolver: ctresolver
    networks:
      - traefik
      - default

  alternate:
    image: schmunk42/nginx-redirect
    restart: always
    environment:
      SERVER_REDIRECT: coursetable.com
    labels:
      traefik.enable: true
      traefik.http.routers.coursetable-alt.rule: Host(`www.coursetable.com`, `beta.coursetable.com`)
      traefik.http.routers.coursetable-alt.tls: true
      traefik.http.routers.coursetable-alt.tls.certResolver: ctresolver
    networks:
      - traefik
      - default

  api:
    image: node:latest
    restart: always
    ports:
      - '4096:4096'
    volumes:
      - ../api:/app
    user: '1000'
    command: sh -c 'cd /app && yarn && yarn start'
    environment:
      GRAPHQL_ENDPOINT: http://graphql-engine:8080/v1/graphql
      MYSQL_HOST: ${MYSQL_HOST?host}
      MYSQL_PORT: ${MYSQL_PORT?port}
      MYSQL_USER: ${MYSQL_USERNAME?username}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD?password}
      MYSQL_DB: yaleplus
      CHALLENGE_PASSWORD: ${CHALLENGE_ENC_PASSWORD?challenge password}
      FERRY_SECRET: ${FERRY_RELOAD_SECRET?ferry reload secret}
    networks:
      - mysql_default
      - default

  frontend:
    build:
      context: ../frontend
      args:
        REACT_APP_UMAMI_WEBSITE_ID: 1fbff7d5-794d-456f-aa1a-61d8f5794b74
        REACT_APP_POSTHOG_TOKEN: KP78eJ-P-nRNQcVeL9pgBPGFt_KXOlCnT7ZwoJ9UDUo
    restart: always
    expose:
      - '5000'

  graphql-engine:
    image: hasura/graphql-engine:latest
    restart: always
    ports:
      - '8085:8080'
    environment:
      HASURA_GRAPHQL_DATABASE_URL: ${FERRY_POSTGRES_URI?ferry db}
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'false'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    networks:
      - ferry_default
      - default

  nginx:
    build: ./nginx
    restart: always
    ports:
      - '8079:8080'
    expose:
      - '8080'
    volumes:
      - ..:/usr/share/nginx/html
      # Overwrite the default configuration. Our conf is based on it
      - ../sysadmin/nginx/docker:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    links:
      - php-fpm
    networks:
      - mysql_default
      - default

  # Ensure php deps are installed
  php:
    build: ./php
    volumes:
      - ..:/var/www/html
    command: sh -c 'php composer.phar install'
    working_dir: /var/www/html

  php-fpm:
    build: ./php
    restart: always
    env_file: ../facebook.env
    environment:
      MYSQL_HOST: ${MYSQL_HOST?host}
      MYSQL_PORT: ${MYSQL_PORT?port}
      MYSQL_USERNAME: ${MYSQL_USERNAME?username}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD?password}
      MYSQL_DATABASE: yale_advanced_oci
    volumes:
      - ..:/usr/share/nginx/html
    networks:
      - mysql_default
      - default

  legacy:
    image: nginx
    restart: always
    ports:
      - '8075:80'
    volumes:
      - ../legacy:/usr/share/nginx/html:ro
    labels:
      traefik.enable: true
      traefik.http.routers.coursetable-legacy.rule: Host(`legacy.coursetable.com`)
      traefik.http.routers.coursetable-legacy.tls: true
      traefik.http.routers.coursetable-legacy.tls.certResolver: ctresolver
    networks:
      - traefik
      - default

networks:
  traefik:
    external: true
  ferry_default:
    external: true
  mysql_default:
    external: true
