on:
  schedule:
    # Runs every Monday at 00:00
    - cron: "0 0 * * 1"

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan CourseTable with Zed Attack Proxy
    steps:
      - name: ZAP main site
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          target: "https://www.coursetable.com"
          
      - name: ZAP API endpoint
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          target: "https://api.coursetable.com"
